
name: Build and push Container images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: bootJar
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} 

    - name: Setup Docker Buildx
      run: docker buildx create --use

    - name: Build and push Container images
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ./Containerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ghcr.io/whitenoise0000/jf-app:latest
          ghcr.io/whitenoise0000/jf-app:${{ github.sha }}

    - name: Delete Old Package Versions
      uses: actions/delete-package-versions@v5.0.0
      with:
        owner: whitenoise0000
        package-name: jf-app
        package-type: container
        min-versions-to-keep: 5
        token: ${{ secrets.GITHUB_TOKEN }}

#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Login to Azure
#      uses: azure/login@v2.2.0
#      with:
#        creds: ${{ secrets.AZURE_CREDENTIALS }}
#
#    - name: Deploy to Azure Container Apps
#      run: |
#        set -e
#        echo "Setting Azure subscription..."
#        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#        echo "Updating Container App..."
#        az containerapp update \
#          --name jf-waf \
#          --resource-group t-jpnwest \
#          --container-name jf-app \
#          --image ghcr.io/whitenoise0000/jf-app:${{ github.sha }} 
